spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  profiles:
    active: local, swagger, oauth # develop_be merge : aws 변경, feature/be/개인branch push : local

server:
  port: 8000
  servlet:
    context-path: /api

jwt:
  secret: cs31313dk3gkblcxo1oslaslzx421kddkcmvi3412wkkklfcxxiqwj131313dkdkskskvbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK


#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
